# permissions for end users to view kafkatopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: env-cd
    app.kubernetes.io/managed-by: kustomize
  name: kafkatopic-viewer-role
rules:
- apiGroups:
  - core.envcd.io
  resources:
  - kafkatopics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.envcd.io
  resources:
  - kafkatopics/status
  verbs:
  - get
