# permissions for end users to edit postgresqldatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: env-cd
    app.kubernetes.io/managed-by: kustomize
  name: postgresqldatabase-editor-role
rules:
- apiGroups:
  - core.envcd.io
  resources:
  - postgresqldatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.envcd.io
  resources:
  - postgresqldatabases/status
  verbs:
  - get
