---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.envcd.io
  resources:
  - environments
  - postgresqldatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.envcd.io
  resources:
  - environments/finalizers
  - postgresqldatabases/finalizers
  verbs:
  - update
- apiGroups:
  - core.envcd.io
  resources:
  - environments/status
  - postgresqldatabases/status
  verbs:
  - get
  - patch
  - update
